name: Silky Wheel Release

on: 
  push:
    branches:
      - main


jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: octakitten/opencb-v01
    steps:
    - run: gh release delete latest -y --cleanup-tag
    - run: gh release create latest dist/*.whl
    #    - uses: actions/upload-artifact@v4
    #  with:
    #    name: opencb-wheel
    #    path: ./dist/*.whl
        
