name: Silky Wheel Release

on: 
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: octakitten/silky-v02
    steps:
    - uses: actions/upload-artifact@v4
      with:
        name: silky-py3-none-any.whl
        path: /silky/dist/silky-*.whl
        if-no-files-found: error
        retention-days: 1
        overwrite: true
    - run: gh release delete latest -y --cleanup-tag
    - run: gh release create latest silky-py3-none-any.whl
    #    - uses: actions/upload-artifact@v4
    #  with:
    #    name: opencb-wheel
    #    path: ./dist/*.whl
        
