name: OpenCB Wheel Release

on: 
  push:
    branches:
      - main


jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: github.com/octakitten/opencb/dockerfile
    steps:
    - uses: actions/checkout@v4
    - uses: actions/upload-artifact@v4
      with:
        name: opencb-wheel
        path: dist/*.whl
